### ISSUE TITLE
Formatting Issue in the HCSB and CSB Versions

### ISSUE THREAD

**Issue by MarkLaBarr** [BibleBot/BibleBot#153]
**Describe the bug**
The HCSB and CSB similarly show up as such:
Psalm 90:10 - Holman Christian Standard Bible (HCSB)
<10> Our lives last seventy yearsor, if we are strong, eighty years. Even the best of them are struggle and sorrow; indeed, they pass quickly and we fly away.
BibleBot 8.0.0

It seems that upon a paragraph break or new line or some such, the space is missing between the end word of the line and the first word of the next line. This occurs in most of every quoted verse.

**To Reproduce**
1. +setversion HCSB (or CSB)
2. Cite practically any Bible verse, especially ones with formatting like quotes or Psalms.

**Expected behavior**
In the example, "years or" instead of "yearsor".

**Screenshots**
Copy and pasted.

**Comment by vypr** [comment]
There's a variety of reasons for this, BibleBot attempts to cut out any extra whitespace around verses and it does end up putting words together like this in poetry sections like Psalms, Proverbs, etc.

I've tried to improve this but the way that Bible Gateway formats poetry is not universal, meaning that each individual version formats it in their own way.

I'll take a look into it and see if there's a way I can make a one-size-fits-all solution.

**Comment by xsrp** [comment]
Out of a happy accident, this has been fixed.
