### ISSUE TITLE
[FEATURE] Language live-reload (owner only)

### ISSUE THREAD

**Issue by SeraphimRP** [BibleBot/BibleBot#163]
**Is your feature request related to a problem? Please describe.**
In order to reload the language files, a full bot restart is required. This is taxing as start-up time is a couple minutes, which is absolutely unnecessary for something this trivial.

**Describe the solution you'd like**
An owner-only `+reload` command that reloads the language files and other appropriate items. Possibly create an argument to specify what to reload (`languages`, `booknames`, to name a few).

**Describe alternatives you've considered**
There is no alternative besides restarting the bot. This isn't a viable option.

**Additional context**
Might be worth creating a function in `src/data/languages.py` to facilitate the language reload. As for the book-names, we could create a call to `asyncio.run()` like we do in `src/bot.py`.

It also might be worth adding this as an option for our translators so that way there's no wait to get new translations, as long as they are committed.

**Comment by RafaCastaneda** [comment]
No Spanish language support?

**Comment by vypr** [comment]
> No Spanish language support?

This is not the appropriate place to ask about this. Please visit our support server.

**Comment by SeraphimRP** [comment]
Closing due to irrelevance.
