### ISSUE TITLE
[BUG] 1 Peter Outputs Verses from Numbers Instead 

### ISSUE THREAD

**Issue by MarkLaBarr** [BibleBot/BibleBot#167]
**Describe the bug**
When sending 1 Pet. 1:1-2 (and other variation of 1 Peter), BibleBot gets a verse from numbers instead.
![Untitled](https://user-images.githubusercontent.com/59465850/80587191-b5c3ae00-8a48-11ea-8734-db18765ca2fd.png)

**Comment by vypr** [comment]
I'm 99% certain the cause of this issue is from [BibleBot/name_scraper](https://github.com/BibleBot/name_scraper). I'll have it fixed tonight alongside other bugfixes.
