### ISSUE TITLE
Feature request: More Bible translations from bibleserver.com

### ISSUE THREAD

**Issue by dpk** [BibleBot/BibleBot#17]
BibleGateway.com’s selection of non-English translations is pretty weak: only the 1545 edition of the Luther bible, for instance, not the 2017 current version.

bibleserver.com has the 2017 Luther bible, Schlachter 2000 (which has the best Psalms translation imo) and many others in German, French, Dutch, Spanish, Italian, etc etc. Its selection of English bibles is much reduced but there are already plenty on biblegateway.

It would be nice to get the Revised English Bible available too, but unfortunately it seems Oxford and Cambridge don’t want anyone to actually use this and make it as hard to get as possible (it’s online at http://www.oxfordbiblicalstudies.com but you need to pay to use it …).

**Comment by vypr** [comment]
I'll look into bibleserver and report back to you on that. As for the Revised English Bible, is it the same thing as the Revised English Version? REV is in BibleBot already, if it's the same.

**Comment by dpk** [comment]
No, the REV seems to be a different one (apparently the 1885 ‘Revised Version’). You can tell the [REB](https://en.wikipedia.org/wiki/Revised_English_Bible) by its very distinctive, lucid translation of John 1:

> In the beginning the Word already was. The Word was in God’s presence, and what God was, the Word was. He was with God at the beginning, and through him all things came to be; without him no created thing came into being. In him was life, and that life was the light of mankind. The light shines in the darkness, and the darkness has never mastered it.

**Comment by vypr** [comment]
I see. I probably won't be able to add the REB nor really consider it because of that subscription model, I'd imagine the copyright on top of that would make BibleBot in a weird legal spot if I were to include it. My apologies.

**Comment by vypr** [comment]
Bibleserver.com certainly could be added, however given the format I will need to create a vector that'll take a "codename" for a book and put it to the right version, or find some other way. I'll place this on hold because this certainly won't be done until v7 when I go about adding other websites as well.

**Comment by vypr** [comment]
Implemented on local branch. You will see these versions (Septuaginta, Lutherbibel 2017, Schlachter 2000) in v7.
