### ISSUE TITLE
[FEATURE] Full verse count array organization for independent randomness source in random verse selection + verse count parameter + quantum random command

### ISSUE THREAD

**Issue by Olliyze** [BibleBot/BibleBot#170]
**Is your feature request related to a problem? Please describe.**
This would make it so you can use an independent randomness source instead of api-bible's. It would make it easier to select a random verse from whatever book(s) you choose, as well as an optional number of verses in that range.

**Describe the solution you'd like**
I imported a verse count.json file and quantum random package to make these features. Then make direct api requests to get the selected verse. Also did a lot of boundary-condition checking for the parameter for the number of verses which caps at 3 and throws an error if larger or subzero. The returned verses are contiguous and limited to the specific chapter.

**Describe alternatives you've considered**
Created quantumrandom as a separate command to test this easier before. I had some troubles using relative python paths for verse count.json so that has to be fixed.

**Additional context**
have a pull request for master branch but it may be better suited for v7. Again, verse count.json must be changed for each user's file path.

**Comment by vypr** [comment]
@Olliyze Question, does this account for missing verses in any translation? For example, translations based on the Textus Receptus (KJV, NKJV, etc.) do not necessarily have the same verses as in the ones based on the Critical Text (RSV, NIV, ESV, NASB, etc.).

**Comment by Olliyze** [comment]
> @Olliyze Question, does this account for missing verses in any translation? For example, translations based on the Textus Receptus (KJV, NKJV, etc.) do not necessarily have the same verses as in the ones based on the Critical Text (RSV, NIV, ESV, NASB, etc.).

No, I don't believe it does. I assumed that the verse counts were the same for all versions. Had only briefly looked into it. My apologies.

**Comment by vypr** [comment]
@Olliyze That's okay though, this is a starting point. A very necessary one. I'll let your PR be the starting point for v9 and we can improve it as we go. I have a feeling that we'll have to have the bot store verses locally instead of live scraping, but this might just be for the best.

**Comment by Olliyze** [comment]
@vypr Perhaps the API for those select books will all return a verse not found error and a different set of contiguous ones could be looped. Probably a fair bit of work still, but might be easier than tracing down the different counts.

**Comment by Olliyze** [comment]
@xsrp Hi, I double checked and noticed that the array access should be based off of the modulo of a whole multiple of the total number of verses. Which could be the total number of verses (31102) or a multiple of that (777550). Currently it's 77777, which means that ~0.2% of verses will be evenly distributed to be skewed towards a doubling of one of the first 227 verses. I may have been using that as a placeholder until I found the verse_count.json file, however I truly apologize for that and hope I can add some other suggestions to make this more sturdy if the user is using a version that you mentioned could have less chapters.

I have two suggestions, one regarding being able to use this properly with the books of varying chapter/verse counts, and the other being that you can load up very large numbers while still being evenly distributed.

For the first, the suggestion would be to create a list of lists, using all the different bible versions from biblegateway, and then creating a list of the respective verse counts for each chapter and book. This could be done by iterating through the URL (assuming that the abbreviations for each book is the same) and iterate through the next abbreviation once it reaches a 404. This would be able to create a versecount.json for every possible book. In hindsight, this is definitely what I should've tried at first, as I remember spending hours going through different archives of book versions that were organized in varying textual formats across the web. Then using the size of that list for the user's respective version, a multiple of it could be used for large numbers to modulo for a random selection; or, the alternative is follows

One statistical method for picking from a list while using large numbers is to simply disregard the selection if it's larger than the list size. If you would want a generated number (or a queue of them, say of a maximum size of 31102 and assume the exceptions  have less than or equal to the number of verses in the standard bibles), then iterate until the first selection that has a valid verse. The advantages to this method include that one can collect the numbers immediately, and that one can do it for whatever book that the user has, assuming that the maximum size encompasses the largest one.

Thank you, and apologies -- I will make sure that any more suggestions are mathematically sound in the future. One example I made a mistake with was that assuming one could iterate through to the nearest valid verse if the user was using a book that has a smaller amount of verses. This would create pockets of verses with higher occurrences if a user was using this book. It was kind of hacky, and for that I also apologize. In my opinion it would still be more random than apibible, so having the independence and power to read through and construct a list based off every bible's verse counts would be the best of both worlds.

**Comment by xsrp** [comment]
@Olliyze I wouldn't stress too hard about it for now. With the rewrite, I want to begin caching verses and scraping whichever ones aren't already. Assuming a version is entirely cached, we could use the data from that in order to get a more accurate number.

Nonetheless, we'll make this work one way or another.

**Comment by xsrp** [comment]
Since trying to calculate the amount of verses in each book in each version is INCREDIBLY impractical at the moment, I've opted to use a truly random Bible verse provider.
