### ISSUE TITLE
[BUG] Books with more than one word in the name do not work for BSB

### ISSUE THREAD

**Issue by fblah** [BibleBot/BibleBot#171]
Books with numbers in the start like 1 John, 2 John, 1 Peter, etc do not work with BSB version.

When using ESV version searching 1 Kings returns 1 Samuel.

Steps to reproduce error:
+setversion bsb
1 john 1:1
+setversion esv
1 kings 1:1

Expected behavior
Expect the corresponding bible verse to be returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/8712033/89741778-c8229e80-dab1-11ea-9ef5-4722e28e2fd4.png)

![image](https://user-images.githubusercontent.com/8712033/89741810-0ddf6700-dab2-11ea-8392-90cea68f0f53.png)

**Comment by vypr** [comment]
The Kings/Samuel portion has been fixed. The BSB issues have not.

**Comment by SeraphimRP** [comment]
Closing due to irrelevance. We intend on bringing back the BSB soon, we just have yet to integrate it. This will eventually become a request of its own.
