### ISSUE TITLE
[BUG] +ccc does not work in DMs

### ISSUE THREAD

**Issue by elisonniven** [BibleBot/BibleBot#172]
**Describe the bug**
Issuing +ccc command doesn't get any response

**To Reproduce**
1. Start a new chat with Biblebot
2. +ccc
3. No response
4. +catechisms list +ccc as an option

**Expected behavior**
Ability to refer ccc

**Comment by vypr** [comment]
While BibleBot does allow you to load the entire catechism for smaller catechisms, it does not do the same thing for the CCC (as the CCC is quite large). You can reference it by using things like `+ccc 1` or `+ccc 1-5`, etc.

**Comment by elisonniven** [comment]
Hi @vypr , `+ccc 1` isn't working either.

**Comment by vypr** [comment]
Couple of things I need to help further.

1. What is your interface language (use `+language`) to find out.
2. What is your User ID? (see https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID- if you need help finding it)
3. What is the shard that the bot is using on your server? (click on the bot in the user list and report what "Shard x / 8" says)

**Comment by elisonniven** [comment]
English
496577333302394883
I'm using a direct chat with Biblebot, not added it to any server.

**Comment by elisonniven** [comment]
Hey @vypr the commands worked after I added the bot to my server, just didn't work in a direct chat.

**Comment by vypr** [comment]
I have a feeling as to why it does that. I'll ensure that it gets fixed.

**Comment by xsrp** [comment]
Fixed in eb56776.
