### ISSUE TITLE
[FEATURE] Add Free Bible Version (FBV)

### ISSUE THREAD

**Issue by synrg** [BibleBot/BibleBot#173]
Please add the Free Bible Version (FBV), a freely licensed new translation available from http://freebibleversion.org/

You may need to contact them regarding formats. I know PDF is probably not suitable, and yet YouVersion / bible.com seem to have the latest beta 3 revision, so I imagine they have other more suitable formats not yet published here. Version 2 did not include the whole Bible, whereas version 3 finally does (YouVersion having finally received updates within the past few weeks).

**Comment by synrg** [comment]
When I looked at their demo application, I found https://scripture.api.bible/ has FBV. Is that one of the API's you support?

**Comment by synrg** [comment]
One more option: following the link to ebible.org from FBV's site, I see that ebible.org has epub & mobi versions that look up to date (i.e. the date is yesterday, Aug 23, 2020) and that should be much easier to work with than scraping the PDF. I guess FBV just hasn't updated their website yet.

**Comment by vypr** [comment]
> APIBible

Given that it's in there, I can get it added today. We already support that API.

**Comment by synrg** [comment]
Excellent!

**Comment by synrg** [comment]
By the way, I wrote FBV this morning to ask them to update their page to say the full version is available, and also requested they list somwhere on their site the API's that have their version to help developers like us.

**Comment by vypr** [comment]
@synrg Much appreciated. Feel free to reach out whenever you need. :)
