### ISSUE TITLE
Undesired output

### ISSUE THREAD

**Issue by suneeshjacob** [BibleBot/BibleBot#19]
I requested for 1 John 1:9 but it posted John 1:9, instead. Kindly rectify. Thanks.

**Comment by vypr** [comment]
Hello,

This bug was brought to my attention earlier today and has been fixed. Could you please confirm if this behavior still continues?

Thank you,
Elliott

**Comment by suneeshjacob** [comment]
Hi,

The issue still continues, as I have tried it just now and found the same behaviour, and therefore it needs fixing, i guess.

Thanks and regards,
Jacob.

**Comment by vypr** [comment]
Jacob,

I saw on the main instance that this behavior existed, which was strange given the fact that the internal testing (which is the same code) doesn't do this. After a few reloads of BibleBot, this seems to have been fixed. Can you confirm?

**Comment by suneeshjacob** [comment]
Elliott,

Yes, it is working properly now.

Thank you,
Jacob.

**Comment by vypr** [comment]
Yeah, it did reappear. There's just no way of debugging it. I tried to make a workaround but we'll find out in time if it works, given how sensitive this issue is. So far it's working.

Thanks,
Elliott
