### ISSUE TITLE
Automatic daily verse is duplicated from load balancing backend.

### ISSUE THREAD

**Issue by PeterPE128** [BibleBot/BibleBot#207]
**The bot sends the Daily Verse twice**
I am not repeating myself a third time

**To Reproduce**
1. Do "+dailyverse set [time two minutes from the actual time]"
2. See error

**Expected behavior**
A single daily verse

**Screenshots**

https://cdn.discordapp.com/attachments/400855639808540673/874266387416240139/image0.jpg

**Comment by PeterPE128** [comment]
Fixed the accidental use of ignoring brackets in the issue text.

**Comment by PeterPE128** [comment]
Thaaat's nooot iiiit

**Comment by SeraphimRP** [comment]
A fix has been deployed on our infrastructure by launching each backend instance one-by-one so that the workaround in 6e21436 works. It hasn't failed since then, so I'll wait a couple days before closing this.

**Comment by SeraphimRP** [comment]
This has been running well for just under a week, I'll consider the issue resolved.

**Comment by SeraphimRP** [comment]
Some errors on AWS cause the backend to be restarted in parallel, rather than a roll out, thus creating the issue again. I'll investigate more today.

**Comment by Rockwall33** [comment]
On 11/18/21 the daily verse sent 1 message, not 2. Now it is back unfortunately. Just wanted to mention the time the issue seemed fixed. Thank you very much!

**Comment by SeraphimRP** [comment]
I've spun off our automatic services into its own subproject, getting it fired up on AWS now. Hopefully this should resolve it.

**Comment by SeraphimRP** [comment]
Should be fixed in 73efbff, keeping this open if we learn anything more.

**Comment by PeterPE128** [comment]
I have not seen any further issues since the comment above. Closing
