### ISSUE TITLE
Support for Threads

### ISSUE THREAD

**Issue by SeraphimRP** [BibleBot/BibleBot#227]
### What would you like to see implemented in BibleBot?

BibleBot should be able to respond to queries in threads to ensure seamless interaction.

Currently, threads are not implemented in the Discord API library we utilize, see https://github.com/DSharpPlus/DSharpPlus/issues/825 for more information.

**Comment by Davi-the-Mudkip** [comment]
Maybe add a button to create a thread from a verse sent by the bot?

**Comment by SeraphimRP** [comment]
@Davi-the-Mudkip This would probably get too spammy to keep up with all the verses. Users can just create a thread manually for whatever they intend on doing.
