### ISSUE TITLE
Inline support for telega-developer to add it into telega

### ISSUE THREAD

**Issue by OrionRandD** [BibleBot/BibleBot#241]
### What would you like to see implemented in BibleBot?

Hi! Great bot app.
We would like to use it inside telega which is a telegram app for Emacs.
Could you add inline support to biblebot?
https://telegram.org/blog/inline-bots

You can talk to zevlg here, if you need further instructions on how to implement
inline support to biblebot
https://github.com/zevlg/telega.el
Thx a lot.

**Comment by SeraphimRP** [comment]
Hiya.

Unfortunately, we aren't the people you're looking for. We're only a Discord bot, we don't have any Telegram apps.

Apologies for the confusion.

**Comment by OrionRandD** [comment]
> Hiya.
> 
> Unfortunately, we aren't the people you're looking for. We're only a Discord bot, we don't have any Telegram apps.
> 
> Apologies for the confusion.

What a pity! Could you implement the bot for Telegram? 
It would be a great add!

**Comment by PeterPE128** [comment]
As of right now, we have no plans for branching out to Telegram, we would rather invest our limited time into maintaining and developing our current projects and environments.

**Comment by OrionRandD** [comment]
> As of right now, we have no plans for branching out to Telegram, we would rather invest our limited time into maintaining and developing our current projects and environments.

Ok. Thx
