### ISSUE TITLE
resources - Athanasian Creed

### ISSUE THREAD

**Issue by Luxei** [BibleBot/BibleBot#272]
### What would you like to see implemented in BibleBot?

It would most helpful during discussions on the topic of the Trinity to be able to load not only the Nicene Creed with /resource resource:nicene, (as well as nicene325) but also, to be able to load the Athanasian Creed for easier reading and discussion than alternatively uploading a hardly readable jpg of the Creed into a chat. Perhaps, due to the length of the Creed, it could be loaded and split into parts for length, such as resource:Athanasian1; resource:Athanasian2… etc). In summary, please add the Athanasian Creed to BibleBot’s resources, it would be much appreciated by many users no doubt. Thank you for all the hard-work on BibleBot!

**Comment by PeterPE128** [comment]
This has already been suggested, see #269.

**Comment by PeterPE128** [comment]
> This has already been suggested, see #269.

^^ For internal reference ^^

**Comment by SeraphimRP** [comment]
Closing as duplicate.
