### ISSUE TITLE
Daily verse webhook should be deleted from database when leaving server.

### ISSUE THREAD

**Issue by SeraphimRP** [BibleBot/BibleBot#273]
### What happened?

Even when BibleBot is kicked/leaves a server, the webhook will still persist in the database and daily verses will still get sent to it.

While we can't delete a webhook when BibleBot leaves a server, we should remove the webhook (and possibly clear all other automatic daily verse preferences) from the database to prevent daily verses from being sent in a server the bot isn't in.

**Comment by PeterPE128** [comment]
Wasn't this intended behaviour? I thought you stated as much a few months back...

**Comment by SeraphimRP** [comment]
> Wasn't this intended behaviour? I thought you stated as much a few months back...

If it was, then I've completely forgotten about it.

I'm not sure if there'd be anyone who would keep automatic daily verses but kick the bot out. We can continue the current system but I feel like detaching the bot from the webhook doesn't make much sense since you can't manage it, the bot isn't there to do that.

I'm open to opinions until this becomes a concrete thing.

**Comment by SeraphimRP** [comment]
Actually, looking at it, the integrated webhook gets removed when the bot gets kicked (because the bot creates it). So this is necessary seeing as there's no preservation of the webhook after the bot leaves.
