### ISSUE TITLE
Daily Verse not being Sent

### ISSUE THREAD

**Issue by ncosta23** [BibleBot/BibleBot#279]
I have two different servers that I use the daily verse for. I first set up BibleBot on April 14. It’s worked fine in each server every day until May 4. Now, it never gets sent. I’ve checked /dailyversestatus, and everything looks good.
![61F414AC-76D9-4B44-8CDD-A662B95D08E7](https://user-images.githubusercontent.com/90484390/167295782-db72739f-e9a8-47b6-99af-d1314f3a2fcb.jpeg)

**Comment by PeterPE128** [comment]
Thank you for your report, we're aware of the issue, and we're trying to investigate why it malfunctions.

As a quote from the message in our status tracking channel.

> Since [Thursday, 5 may 2022, 10:00 UTC], we’ve been aware of issues with our automatic daily verse service preventing verses from being sent. There is a pattern to some degree but more investigation is required.

**Comment by ncosta23** [comment]
Not sure if you made a code change or not since the issue’s still open, but it’s working now. And if you did fix it, thank you!

**Comment by SeraphimRP** [comment]
This may be resolved with a recent dependency update, we'll monitor for a bit longer before we count it fixed. :)

**Comment by SeraphimRP** [comment]
With a bit over 3 days, we'll consider this fixed.
