### ISSUE TITLE
Feature Request: Open-Source API

### ISSUE THREAD

**Issue by tmgkopczyk** [BibleBot/BibleBot#283]
### What would you like to see implemented in BibleBot?

Is it possible to create an open-source API for developers to use in their own projects?

**Comment by SeraphimRP** [comment]
I like the concept, but the main issue is that there would be a lot of legal hurdles to making this worthwhile. Our licensing agreements only allow us to use translations solely on the BibleBot product. These agreements aren't blanket approvals for redistribution however we feel like.

There are a couple of APIs out there already - there's the closed-source API.Bible that we use, and there's a few open-source APIs you can find on GitHub.

Unfortunately, this really isn't something we have the resources to achieve currently. If things change, we get more hands on deck and more income flow, then we could be in a better position to work something out. Until then, I'll have to close this.
