### ISSUE TITLE
World English Bible (WEB) with Apocrypha 

### ISSUE THREAD

**Issue by Luxei** [BibleBot/BibleBot#285]
### What Bible version would you like to see added in BibleBot?

I would like to see the World English Bible (WEB) with Apocrypha as featured in the YouVersion app to be added to Bibel Bot.

**Comment by SeraphimRP** [comment]
There's a handful of WEB's in API.Bible, I'll need to take a look and see which one has the additional books. This should be a painless addition if one exists on there.

**Comment by SeraphimRP** [comment]
Actually, I think I'll replace our current WEB with one from API.Bible, since it has the apocrypha and no need to create a separate version for this imo.

**Comment by SeraphimRP** [comment]
WEB will now use the API.Bible-provided one that includes the apocrypha. It is live in the bot as of writing.
