### ISSUE TITLE
Text order when quoting (longer) text

### ISSUE THREAD

**Issue by michaeldenijs** [BibleBot/BibleBot#70]
Was using this excellent bot, a small bug happened.
I quoted Luke 2:22–40, instead of the bot starting with 22-31 it started with 32-40 putting it in the 'opposite' order. Is this problem new or well known? My apologies if it's already a known issue, just thought I'd report it here just in case.

Kind regards,
Mike

**Comment by michaeldenijs** [comment]
Good to hear, thanks for the amazing bot!

**Comment by vypr** [comment]
This issue will remain open until I write a commit that fixes it, just so I don't forget.

**Comment by vypr** [comment]
I believe this is fixed in v7.1. Additional testing will be needed.
