### ISSUE TITLE
Add references

### ISSUE THREAD

**Issue by cosminghitea** [BibleBot/BibleBot#72]
Hello I would be nice if we would have references in the bot.

**Comment by vypr** [comment]
Like cross-references?

**Comment by cosminghitea** [comment]
https://www.biblegateway.com/passage/?search=Geneza+1%3A1&version=RMNN here's an example

**Comment by vypr** [comment]
I still don't quite understand, do you mean cross-references or the ability to reference verses?

If you mean the latter, that is the primary function of BibleBot, just say a reference and it'll give you it.

**Comment by cosminghitea** [comment]
Cross-references then

**Comment by vypr** [comment]
So the reason why we don't have cross-references is because there's really no place to put them. And for some passages you can have a **ton** of cross-references. BibleBot isn't meant to be a study tool and so implementing this doesn't seem necessary.

**Comment by cosminghitea** [comment]
Ok then thanks
