### ISSUE TITLE
The Bot can't parse any verse from "Song of Songs"

### ISSUE THREAD

**Issue by oshaboy** [BibleBot/BibleBot#82]
**Describe the bug**
The bot can't echo any verse from Song of Solomon aka. Song of Songs

**To Reproduce**
type "Song of Songs 1:5" or "Song of Solomon 1:5" and neither will work

**Expected behavior**
I expect Bible Bot to echo a verse from Song of Songs

**Comment by vypr** [comment]
This is fixed in v7.1 which will be released soon.

**Comment by oshaboy** [comment]
Is the bug fixed yet?

**Comment by vypr** [comment]
It is fixed in v8, v8 is not released yet. Please be patient as there is lots more content that has to be put in before release.
